export const categoriesList = [
  {
    categoria_nome: 'Category 1',
    categoria_id: '1',
    integracoes: [
      {
        integracao_id: '1',
        api_empresa: 'Empresa 1',
        status: 1,
        cron: 0,
        responsavel: {
          nome: 'responsável pela conta',
          email: 'responsavel@email.com',
          telefone: ['999999999', '988888888'],
        },
        anexo: 'link para o arquivo',
        clientes: [
          {
            id: '1',
            nome: 'Cliente 1',
            status: 1,
            cron: 0,
            responsavel: {
              nome: 'responsável pela conta',
              email: 'responsavel@email.com',
              telefone: ['999999999', '988888888'],
            },
            host: 'Host',
            token: '123456abcdef',
            username: 'username',
            password: 'password',
            client_id: '1',
            client_Secret: 'secret',
            grant_type: 'grant type',
            ip: '123123123',
            porta: '123123',
            contra_senha: 'contra senha',
            identificador: '123qwe',
            plano: 'plano(contrato)',
            produto: 'produto(pacote)',
          },
          {
            id: '2',
            nome: 'Cliente 2',
            status: 1,
            cron: 0,
            responsavel: {
              nome: 'responsável pela conta',
              email: 'responsavel@email.com',
              telefone: ['999999999', '988888888'],
            },
            host: 'Host',
            token: '123456abcdef',
            username: 'username',
            password: 'password',
            client_id: '1',
            client_Secret: 'secret',
            grant_type: 'grant type',
            ip: '123123123',
            porta: '123123',
            contra_senha: 'contra senha',
            identificador: '123qwe',
            plano: 'plano(contrato)',
            produto: 'produto(pacote)',
          },
        ],
      },
      {
        integracao_id: '2',
        api_empresa: 'Empresa 2',
        status: 1,
        cron: 0,
        responsavel: {
          nome: 'responsável pela conta',
          email: 'responsavel@email.com',
          telefone: ['999999999', '988888888'],
        },
        anexo: 'link para o arquivo',
        clientes: [
          {
            id: '3',
            nome: 'Cliente 3',
            status: 1,
            cron: 0,
            responsavel: {
              nome: 'responsável pela conta',
              email: 'responsavel@email.com',
              telefone: ['999999999', '988888888'],
            },
            host: 'Host',
            token: '123456abcdef',
            username: 'username',
            password: 'password',
            client_id: '1',
            client_Secret: 'secret',
            grant_type: 'grant type',
            ip: '123123123',
            porta: '123123',
            contra_senha: 'contra senha',
            identificador: '123qwe',
            plano: 'plano(contrato)',
            produto: 'produto(pacote)',
          },
          {
            id: '4',
            nome: 'Cliente 4',
            status: 1,
            cron: 0,
            responsavel: {
              nome: 'responsável pela conta',
              email: 'responsavel@email.com',
              telefone: ['999999999', '988888888'],
            },
            host: 'Host',
            token: '123456abcdef',
            username: 'username',
            password: 'password',
            client_id: '1',
            client_Secret: 'secret',
            grant_type: 'grant type',
            ip: '123123123',
            porta: '123123',
            contra_senha: 'contra senha',
            identificador: '123qwe',
            plano: 'plano(contrato)',
            produto: 'produto(pacote)',
          },
        ],
      },
    ],
  },
  {
    categoria_nome: 'Category 2',
    categoria_id: '2',
    integracoes: [
      {
        integracao_id: '3',
        api_empresa: 'Empresa 3',
        status: 1,
        cron: 0,
        responsavel: {
          nome: 'responsável pela conta',
          email: 'responsavel@email.com',
          telefone: ['999999999', '988888888'],
        },
        anexo: 'link para o arquivo',
        clientes: [
          {
            id: '5',
            nome: 'Cliente 5',
            status: 1,
            cron: 0,
            responsavel: {
              nome: 'responsável pela conta',
              email: 'responsavel@email.com',
              telefone: ['999999999', '988888888'],
            },
            host: 'Host',
            token: '123456abcdef',
            username: 'username',
            password: 'password',
            client_id: '1',
            client_Secret: 'secret',
            grant_type: 'grant type',
            ip: '123123123',
            porta: '123123',
            contra_senha: 'contra senha',
            identificador: '123qwe',
            plano: 'plano(contrato)',
            produto: 'produto(pacote)',
          },
          {
            id: '6',
            nome: 'Cliente 6',
            status: 1,
            cron: 0,
            responsavel: {
              nome: 'responsável pela conta',
              email: 'responsavel@email.com',
              telefone: ['999999999', '988888888'],
            },
            host: 'Host',
            token: '123456abcdef',
            username: 'username',
            password: 'password',
            client_id: '1',
            client_Secret: 'secret',
            grant_type: 'grant type',
            ip: '123123123',
            porta: '123123',
            contra_senha: 'contra senha',
            identificador: '123qwe',
            plano: 'plano(contrato)',
            produto: 'produto(pacote)',
          },
        ],
      },
      {
        integracao_id: '4',
        api_empresa: 'Empresa 4',
        status: 1,
        cron: 0,
        responsavel: {
          nome: 'responsável pela conta',
          email: 'responsavel@email.com',
          telefone: ['999999999', '988888888'],
        },
        anexo: 'link para o arquivo',
        clientes: [
          {
            id: '7',
            nome: 'Cliente 7',
            status: 1,
            cron: 0,
            responsavel: {
              nome: 'responsável pela conta',
              email: 'responsavel@email.com',
              telefone: ['999999999', '988888888'],
            },
            host: 'Host',
            token: '123456abcdef',
            username: 'username',
            password: 'password',
            client_id: '1',
            client_Secret: 'secret',
            grant_type: 'grant type',
            ip: '123123123',
            porta: '123123',
            contra_senha: 'contra senha',
            identificador: '123qwe',
            plano: 'plano(contrato)',
            produto: 'produto(pacote)',
          },
          {
            id: '8',
            nome: 'Cliente 8',
            status: 1,
            cron: 0,
            responsavel: {
              nome: 'responsável pela conta',
              email: 'responsavel@email.com',
              telefone: ['999999999', '988888888'],
            },
            host: 'Host',
            token: '123456abcdef',
            username: 'username',
            password: 'password',
            client_id: '1',
            client_Secret: 'secret',
            grant_type: 'grant type',
            ip: '123123123',
            porta: '123123',
            contra_senha: 'contra senha',
            identificador: '123qwe',
            plano: 'plano(contrato)',
            produto: 'produto(pacote)',
          },
        ],
      },
    ],
  },
];

// ANTIGO
// {
//   category_name: 'Category 2',
//   category_id: '2',
//   integrations: [
//     {
//       integration_name: 'Integration 2.1',
//       integration_id: '1',
//       status: 1,
//       cron: 1,
//       manager: {
//         name: 'responsável pela conta',
//         email: 'responsavel@email.com',
//         phone: ['999999999', '988888888'],
//       },
//       attachments: {
//         type: 'tipo de anexo',
//         link: 'link para o arquivo',
//       },
//       clients: [
//         {
//           client_name: 'Cliente 2.1',
//           client_id: '1',
//           status: 1,
//         },
//         {
//           client_name: 'Cliente 2',
//           client_id: '2',
//           status: 1,
//         },
//       ],
//     },
//     {
//       integration_name: 'Integration 2',
//       integration_id: '2',
//       status: 1,
//       cron: 1,
//       manager: {
//         name: 'responsável pela conta',
//         email: 'responsavel@email.com',
//         phone: ['999999999', '988888888'],
//       },
//       attachments: {
//         type: 'tipo de anexo',
//         link: 'link para o arquivo',
//       },
//       clients: [
//         {
//           client_name: 'Cliente 3',
//           client_id: '3',
//           status: 1,
//         },
//         {
//           client_name: 'Cliente 4',
//           client_id: '4',
//           status: 1,
//         },
//         {
//           client_name: 'Cliente 5',
//           client_id: '5',
//           status: 1,
//         },
//       ],
//     },
//   ],
// },
// {
//   category_name: 'Category 3',
//   category_id: '3',
//   integrations: [
//     {
//       integration_name: 'Integration 3.1',
//       integration_id: '1',
//       status: 1,
//       cron: 1,
//       manager: {
//         name: 'responsável pela conta',
//         email: 'responsavel@email.com',
//         phone: ['999999999', '988888888'],
//       },
//       attachments: {
//         type: 'tipo de anexo',
//         link: 'link para o arquivo',
//       },
//       clients: [
//         {
//           client_name: 'Cliente 3.1',
//           client_id: '1',
//           status: 1,
//         },
//         {
//           client_name: 'Cliente 2',
//           client_id: '2',
//           status: 1,
//         },
//       ],
//     },
//     {
//       integration_name: 'Integration 2',
//       integration_id: '2',
//       status: 1,
//       cron: 1,
//       manager: {
//         name: 'responsável pela conta',
//         email: 'responsavel@email.com',
//         phone: ['999999999', '988888888'],
//       },
//       attachments: {
//         type: 'tipo de anexo',
//         link: 'link para o arquivo',
//       },
//       clients: [
//         {
//           client_name: 'Cliente 3',
//           client_id: '3',
//           status: 1,
//         },
//         {
//           client_name: 'Cliente 4',
//           client_id: '4',
//           status: 1,
//         },
//         {
//           client_name: 'Cliente 5',
//           client_id: '5',
//           status: 1,
//         },
//       ],
//     },
//     {
//       integration_name: 'Integration 3',
//       integration_id: '3',
//       status: 1,
//       cron: 1,
//       manager: {
//         name: 'responsável pela conta',
//         email: 'responsavel@email.com',
//         phone: ['999999999', '988888888'],
//       },
//       attachments: {
//         type: 'tipo de anexo',
//         link: 'link para o arquivo',
//       },
//       clients: [
//         {
//           client_name: 'Cliente 6',
//           client_id: '6',
//           status: 0,
//         },
//       ],
//     },
//   ],
// },
